# Location: productservice/src/main/resources/application.yml
spring:
  datasource:
    # H2 In-Memory Database Configuration
    url: jdbc:h2:mem:productdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa # Default H2 username
    password: '' # Default H2 password (empty)
    
  jpa:
    hibernate:
      
      ddl-auto: update
    
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 9090
